security:
    encoders:
        'FOS\UserBundle\Model\UserInterface': sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/

            facebook:
                user_provider: ruch_jow_user.user_provider
                login_path: "/login/check-facebook"

            form_login:
                provider:   fos_userbundle
                login_path: /login
                check_path: /login_check
                csrf_provider: form.csrf_provider
                success_handler: ruch_jow_ajax_auth.auth_handler
                failure_handler: ruch_jow_ajax_auth.auth_handler
                default_target_path: app_main_page

            logout:
                path: /logout
#                target: app_main_page
                invalidate_session: false
                success_handler: ruch_jow_ajax_auth.auth_handler
            anonymous: true

            switch_user:  false

            remember_me:
                key:      "%secret%"
                lifetime: 2592000 # 30 days in seconds
                path:     /
                domain:   ~

        login:
            pattern:  ^/login$
            security: false

            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER



    access_control:
        # SECURITY
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/registration/facebook$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/facebook$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/users/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/users/register/confirm$, role: IS_AUTHENTICATED_ANONYMOUSLY }


#        # FOUNDATION
        - { path: "^/foundation/partial/[.\-a-zA-Z0-9_]+$", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/foundation/cif/auth_forms_data$,      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/foundation/cif/user_roles$,           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/foundation/cif/user_public_data/[^/]+$,     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/foundation/cif/user_fvu/(nick|email)$, role: IS_AUTHENTICATED_ANONYMOUSLY } #user_field_value_unique
        - { path: ^/foundation/cif/user_fvpc/(password)$, role: IS_AUTHENTICATED_ANONYMOUSLY } #user_field_value_check
        - { path: ^/foundation/cif/points_definitions$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/foundation/cif/user_points_history$, role: ROLE_REGISTERED_USER }
#        - { path: ^/cif/foundation/data/rates$,           role: IS_AUTHENTICATED_ANONYMOUSLY } #exception for rates
##        - { path: ^/cif/foundation/data/[a-zA-Z0-9_-]+$,  role: ROLE_REGISTERED_USER }


#
#        # APP
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/parameters.js$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # APP markers
        - { path: ^/markers/cif/all$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # APP Jow Events
        - { path: ^/jow_events/cif/list(/(\d+)?(/(\d+)?)?)?$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # APP angular partials
        - { path: "^/partial/[.\-a-zA-Z0-9_]+$", role: IS_AUTHENTICATED_ANONYMOUSLY }


        # Actions
        - { path: "^/ajax/organise_event$",      role: ROLE_REGISTERED_USER }
        - { path: "^/ajax/organise_referendum_point$", role: ROLE_REGISTERED_USER }
#        - { path: "^/ajax/distribute_leaflets$", role: ROLE_REGISTERED_USER }

        # TERRITORIAL UNITS
        - { path: ^/cif/tu/ajax/communes$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cif/tu/ajax/countries$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cif/tu/ajax/search/tu$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cif/tu/geo_shapes,     role: IS_AUTHENTICATED_ANONYMOUSLY }

        # TERRITORIAL UNITS
        - { path: ^/cif/localgov/ajax/support$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # POINTS
        - { path: ^/cif/pts, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # USER (& ORGANISATIONS)
        - { path: ^/cif/user/ajax/organisations$,              role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cif/user/ajax/support$,                    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cif/user/ajax/support/confirm$,            role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cif/user/ajax/password/forgot$,            role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cif/user/ajax/password/check_reset_token$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cif/user/ajax/password/set_new$,           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cif/user/ajax/pre_signed_data$,            role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/cif/user/ajax/update$,                 role: ROLE_REGISTERED_USER }
        - { path: ^/cif/user/ajax/invite_friends$,         role: ROLE_REGISTERED_USER }
        - { path: ^/cif/user/ajax/remove/account$,         role: ROLE_REGISTERED_USER }
        - { path: ^/cif/user/ajax/remove/account/confirm$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cif/user/ajax/connect_facebook$,       role: ROLE_REGISTERED_USER }
        - { path: ^/cif/user/ajax/disconnect_facebook$,       role: ROLE_REGISTERED_USER }

        # STATISTICS
        - { path: ^/cif/statistics/basic_statistics$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cif/statistics/unit_statistics$,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cif/statistics/ranks$,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cif/statistics/user_statistics$,  role: ROLE_REGISTERED_USER }

        # Transferuj.pl
        - { path: ^/transferuj_pl/encode$,   role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/transferuj_pl/feedback$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # FEEDBACK
        - { path: ^/cif/feedback/create$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # MESSAGES
        - { path: ^/cif/messages/ajax/folders$, role: ROLE_REGISTERED_USER }
        - { path: ^/cif/messages/ajax/messages/(\#|[a-zA-Z])+/\d+/[1-9]\d*$, role: ROLE_REGISTERED_USER }
        - { path: ^/cif/messages/ajax/message/get/[1-9]\d*$, role: ROLE_REGISTERED_USER }
        - { path: ^/cif/messages/ajax/message/send$, role: ROLE_REGISTERED_USER }

        #FEED
        - { path: ^/cif/feed/announcements$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # REDIRECTIONS
        - { path: ^/wsparcie$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # BACKEND
        - { path: ^/backend/?$, role: ROLE_BACKEND }
        - { path: ^/backend/cif/feedback$, role: ROLE_BACKEND_FEEDBACK }
        - { path: ^/backend/cif/users/unverified$, role: ROLE_USERS_UNVERIFIED }
        - { path: "^/backend/cif/user/data/[.\-_ a-zęóąśłżźćńA-ZĘÓĄŚŁŻŹĆŃ0-9_]+$", role: ROLE_USER_DATA }
        - { path: ^/backend/cif/user/search$, role: ROLE_USER_DATA }
        - { path: ^/backend/cif/tasks$, role: ROLE_BACKEND_TASKS }
        - { path: ^/backend/cif/user_roles$, role: ROLE_BACKEND }

        - { path: ^/backend/cif/user/points_add_options$, role: ROLE_ADD_POINTS }
        - { path: ^/backend/cif/user/points_add$, role: ROLE_ADD_POINTS }
        - { path: ^/backend/cif/user/donation_add$, role: ROLE_ADD_DONATION }

        - { path: ^/backend/cif/referendumPoints/list$, role: ROLE_REFERENDUM_POINTS }
        - { path: ^/backend/cif/referendumPoints/update$, role: ROLE_REFERENDUM_POINTS_ADMIN }

        - { path: ^/backend/cif/jowEvents/list$, role: ROLE_JOW_EVENTS }
        - { path: ^/backend/cif/jowEvents/update$, role: ROLE_JOW_EVENTS_ADMIN }
        - { path: ^/backend/cif/jowEvents/remove$, role: ROLE_JOW_EVENTS_ADMIN }



        - { path: "^/backend/partial/[.\-a-zA-Z0-9_]+$", role: ROLE_BACKEND }

        # DEFAULTS
        - { path: ^/, role: ROLE_NO_ACCESS }

    role_hierarchy:
        ROLE_BACKEND:
            - ROLE_BACKEND_FEEDBACK
            - ROLE_USERS_UNVERIFIED
            - ROLE_USER_DATA
            - ROLE_BACKEND_TASKS
            - ROLE_REFERENDUM_POINTS
            - ROLE_JOW_EVENTS

        ROLE_BACKEND_ADMIN:
            - ROLE_BACKEND
            - ROLE_ADD_POINTS
            - ROLE_ADD_DONATION
            - ROLE_REFERENDUM_POINTS_ADMIN
            - ROLE_JOW_EVENTS_ADMIN

        ROLE_ADMIN:
            - ROLE_BACKEND_ADMIN

        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH


ruch_jow_page_foundation:
    exposed_user_roles:
        - ROLE_REGISTERED_USER

ruch_jow_backend:
    exposed_user_roles:
        - ROLE_ADD_POINTS
        - ROLE_ADD_DONATION
        - ROLE_REFERENDUM_POINTS_ADMIN
        - ROLE_BACKEND_ADMIN


