parameters:
    ruch_jow_angular_security.kernel_listener.class: RuchJow\AngularSecurityBundle\Listener\KernelListener
    ruch_jow_angular_security.service.class: RuchJow\AngularSecurityBundle\Service\AngularSecurity

services:
    ruch_jow_angular_security.kernel_listener:
        class: %ruch_jow_angular_security.kernel_listener.class%
        arguments:
            - "@ruch_jow_angular_security.service"
            - "%ruch_jow_angular_security.xsrf_cookie_name%"
            - "%ruch_jow_angular_security.xsrf_header_name%"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 1000 }
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 1000 }


    ruch_jow_angular_security.service:
        class: %ruch_jow_angular_security.service.class%
        arguments:
            - "@form.csrf_provider"
            - "@request_stack"
            - "%ruch_jow_angular_security.xsrf_cookie_name%"
            - "%ruch_jow_angular_security.xsrf_header_name%"